sonar.projectKey=api-system-coursers
sonar.sources=.
sonar.language=py
sonar.python.coverage.reportPaths=coverage.xml
sonar.exclusions=**/migrations/**, **/tests/**, manage.py, core/wsgi.py, core/asgi.py